# Generated by Django 4.0 on 2022-04-26 22:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('types', models.CharField(choices=[('AIRTIME', 'AIRTIME'), ('DATA', 'DATA'), ('POWER', 'POWER')], max_length=300)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillsRecharge',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('recieving_id', models.CharField(max_length=300)),
                ('desposit_address', models.CharField(max_length=300)),
                ('bills_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bills')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
