# Generated by Django 4.0.4 on 2022-04-30 17:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsrecharge',
            name='is_abadoned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('OVER_PAID', 'OVER_PAID')], max_length=300)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.billsrecharge')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
