# Generated by Django 4.0.4 on 2022-04-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_billsrecharge_is_abadoned_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsrecharge',
            name='transaction_receipt_email',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
