# Generated by Django 4.0.4 on 2022-04-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_billsrecharge_transaction_receipt_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsrecharge',
            name='expected_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
        ),
    ]
