# Generated by Django 4.0.4 on 2022-04-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_billsrecharge_expected_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsrecharge',
            name='recieving_currency',
            field=models.CharField(choices=[('TRX', 'TRX')], default='TRX', max_length=300, null=True),
        ),
    ]
