# Generated by Django 4.0.4 on 2022-05-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_billsrecharge_recieving_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsrecharge',
            name='recieving_currency',
            field=models.CharField(choices=[('TRX', 'TRX'), ('LTC', 'LTC')], default='TRX', max_length=300, null=True),
        ),
    ]
