# Generated by Django 4.0.4 on 2022-05-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_billsrecharge_is_redeemed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billsrecharge',
            old_name='is_redeemed',
            new_name='is_paid',
        ),
    ]
