# Generated by Django 4.0.4 on 2022-05-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_is_redeemed_billsrecharge_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsrecharge',
            name='reference',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
