# Generated by Django 4.0.4 on 2022-05-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_acceptedcrypto'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsrecharge',
            name='related_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.acceptedcrypto'),
        ),
    ]
