# Generated by Django 4.0.4 on 2022-05-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_billsrecharge_related_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billsrecharge',
            name='recieving_currency',
        ),
    ]
