# Generated by Django 4.0.4 on 2022-05-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_billsrecharge_recieving_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptedcrypto',
            options={'verbose_name_plural': 'Accepted Crypto'},
        ),
        migrations.AlterModelOptions(
            name='bills',
            options={'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterModelOptions(
            name='billsrecharge',
            options={'verbose_name_plural': 'Bills Recharge'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name_plural': 'Transaction'},
        ),
    ]
