# Generated by Django 4.0.4 on 2022-05-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_acceptedcrypto_options_alter_bills_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bills',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterModelOptions(
            name='billsrecharge',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Bills Recharge'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Transaction'},
        ),
    ]
