# Generated by Django 4.0.4 on 2022-05-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_bills_options_alter_billsrecharge_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcrypto',
            name='ticker',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
