# Generated by Django 4.0.4 on 2022-05-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_acceptedcrypto_ticker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='buying_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='recieve_amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
    ]
