# Generated by Django 4.0.4 on 2022-05-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_transaction_bill_payment_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcrypto',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='network',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
