# Generated by Django 4.0.4 on 2022-05-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_acceptedcrypto_image_network_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsrecharge',
            name='expected_amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
    ]
