# Generated by Django 4.0.4 on 2022-05-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_billsrecharge_expected_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='instant_order_status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('CANCELLED', 'CANCELLED')], default='DONE', max_length=300),
        ),
    ]
