# Generated by Django 4.0.4 on 2022-05-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_transaction_instant_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='status',
            new_name='bill_payment_status',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='instant_sell_response',
            new_name='instant_order_response',
        ),
    ]
