# Generated by Django 4.0.4 on 2022-05-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_status_transaction_bill_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
