# Generated by Django 4.0.4 on 2022-05-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_transaction_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='instant_order_id',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
