# Generated by Django 4.0.4 on 2022-05-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_billsrecharge_blockchain_deposit_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsrecharge',
            name='blockchain_deposit_status',
            field=models.CharField(blank=True, choices=[('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED'), ('CONFIRMATION', 'CONFIRMATION')], default='CONFIRMED', max_length=300, null=True),
        ),
    ]
