# Generated by Django 4.0.4 on 2022-05-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_billsrecharge_blockchain_deposit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsrecharge',
            name='blockchain_deposit_status',
            field=models.CharField(blank=True, choices=[('SUCCESSFUL', 'SUCCESSFUL'), ('REJECTED', 'REJECTED'), ('PENDING', 'PENDING'), ('CONFIRMATION', 'CONFIRMATION')], default='PENDING', max_length=300, null=True),
        ),
    ]
