# Generated by Django 4.0.4 on 2022-05-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_billsrecharge_blockchain_deposit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='types',
            field=models.CharField(choices=[('AIRTIME', 'AIRTIME'), ('GIFTCARD', 'GIFTCARD'), ('DATA', 'DATA'), ('POWER', 'POWER')], max_length=300),
        ),
    ]
