# Generated by Django 4.0.4 on 2022-05-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_bills_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='currency',
            field=models.CharField(choices=[('DOLLARS', 'DOLLARS'), ('NAIRA', 'NAIRA')], default='NAIRA', max_length=300),
        ),
    ]
