# Generated by Django 4.0.4 on 2022-05-19 12:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_bills_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.billsrecharge'),
        ),
        migrations.CreateModel(
            name='POSWithdrawal',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('desposit_address', models.CharField(max_length=300)),
                ('expected_amount', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('blockchain_deposit_status', models.CharField(blank=True, choices=[('SUCCESSFUL', 'SUCCESSFUL'), ('REJECTED', 'REJECTED'), ('PENDING', 'PENDING'), ('CONFIRMATION', 'CONFIRMATION')], default='PENDING', max_length=300, null=True)),
                ('is_overpaid', models.BooleanField(default=False)),
                ('is_abadoned', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('instant_order_response', models.JSONField(default=dict)),
                ('instant_order_status', models.CharField(choices=[('DONE', 'DONE'), ('CONFIRM', 'CONFIRM'), ('CANCELLED', 'CANCELLED')], default='DONE', max_length=300)),
                ('instant_order_id', models.CharField(blank=True, max_length=300)),
                ('related_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.acceptedcrypto')),
            ],
            options={
                'verbose_name_plural': 'Withdrawal Request',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='pos_withdrawal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.poswithdrawal'),
        ),
    ]
