# Generated by Django 4.0.4 on 2022-05-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_transaction_bill_poswithdrawal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedcrypto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
