# Generated by Django 4.0.4 on 2022-05-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_acceptedcrypto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poswithdrawal',
            name='is_underpaid',
            field=models.BooleanField(default=False),
        ),
    ]
