# Generated by Django 4.0.4 on 2022-06-04 12:48

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_poswithdrawal_is_underpaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('blockchain_type', models.CharField(blank=True, choices=[('BEP20', 'BEP20')], default='BEP20', max_length=300, null=True)),
                ('desposit_address', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'WalletAddress',
                'ordering': ('-created',),
            },
        ),
    ]
