# Generated by Django 4.0.4 on 2022-06-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_walletaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcrypto',
            name='is_bep_20',
            field=models.BooleanField(default=False),
        ),
    ]
