# Generated by Django 4.0.4 on 2022-06-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_acceptedcrypto_is_bep_20'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poswithdrawal',
            name='desposit_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.walletaddress'),
        ),
    ]
