# Generated by Django 4.0.4 on 2022-06-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_poswithdrawal_desposit_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='poswithdrawal',
            name='reference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
