# Generated by Django 4.0.4 on 2022-06-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_poswithdrawal_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='related_to',
            field=models.CharField(choices=[('BILL_PAYMENT', 'BILL_PAYMENT'), ('POS_WITHDRAWAL', 'POS_WITHDRAWAL')], default='BILL_PAYMENT', max_length=300),
        ),
    ]
