# Generated by Django 4.0.4 on 2022-06-11 20:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_transaction_pos_withdrawal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poswithdrawal',
            options={'ordering': ('-created',), 'verbose_name_plural': 'POSWithdrawal Request'},
        ),
        migrations.CreateModel(
            name='POSTransaction',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('pos_withdrawal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.poswithdrawal')),
            ],
            options={
                'verbose_name_plural': 'POSTransaction Request',
                'ordering': ('-created',),
            },
        ),
    ]
